/**
 * Mock API client for testing hooks and components.
 *
 * AUTO-GENERATED by scripts/generate-client.ts
 * Do not edit this file manually - changes will be overwritten.
 */

import { vi, type Mock } from 'vitest'
import type { CanopyApiClient } from '../client'
import type { ApiResponse } from '../types'
import type { BranchDeleteResponse, BranchListResponse, BranchResponse } from '../branch'
import type { BranchMergeResponse } from '../branch-status'
import type { AddCommentResponse, CommentsResponse, ResolveCommentResponse } from '../comments'
import type {
  ContentReadResponse,
  ContentWriteResponse,
  ReferenceValidationResponse,
} from '../content'
import type { ReferenceOptionsResponse } from '../reference-options'
import type { ResolveReferencesResponse } from '../resolve-references'
import type { EntriesResponse } from '../entries'
import type { AssetDeleteResponse, AssetUploadResponse, AssetsListResponse } from '../assets'
import type { ListGroupsResponse, PermissionsResponse, SearchUsersResponse } from '../permissions'
import type {
  ExternalGroupsResponse,
  InternalGroupsResponse,
  UpdateInternalGroupsResponse,
} from '../groups'
import type { UserInfoResponse } from '../user'
import type { CreateBranchBody, UpdateBranchAccessBody } from '../branch'

/**
 * Type utility to convert CanopyApiClient methods to Vitest mocks.
 */
export type MockApiClient = {
  [K in keyof CanopyApiClient]: CanopyApiClient[K] extends Record<string, any>
    ? {
        [M in keyof CanopyApiClient[K]]: CanopyApiClient[K][M] extends (
          ...args: infer Args
        ) => infer Return
          ? Mock<Args, Return>
          : never
      }
    : never
}

/**
 * Create a mock API client with all methods as vi.fn().
 */
export function createMockApiClient(): MockApiClient {
  return {
    branches: {
      list: vi.fn().mockResolvedValue(mockSuccess({ branches: [] })),
      create: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      delete: vi.fn().mockResolvedValue(mockSuccess({ deleted: true })),
      updateAccess: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
    },

    workflow: {
      withdraw: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      requestChanges: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      approve: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'approved',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      markMerged: vi
        .fn()
        .mockResolvedValue(mockSuccess({ branch: { name: 'test-branch', status: 'archived' } })),
      getStatus: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      submit: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'submitted',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
    },

    comments: {
      list: vi.fn().mockResolvedValue(mockSuccess({ threads: [] })),
      add: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({ threadId: 'mock-thread-id', commentId: 'mock-comment-id' }),
        ),
      resolve: vi.fn().mockResolvedValue(mockSuccess({ resolved: true })),
    },

    content: {
      read: vi.fn().mockResolvedValue(mockSuccess({ format: 'json', data: {} })),
      write: vi.fn().mockResolvedValue(mockSuccess({ format: 'json', data: {} })),
      validateReferences: vi.fn().mockResolvedValue(mockSuccess({ valid: true })),
      getReferenceOptions: vi.fn().mockResolvedValue(mockSuccess({ options: [] })),
      resolveReferences: vi.fn().mockResolvedValue(mockSuccess({ resolved: {} })),
    },

    entries: {
      list: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({ collections: [], entries: [], pagination: { hasMore: false, limit: 50 } }),
        ),
    },

    assets: {
      list: vi.fn().mockResolvedValue(mockSuccess({ assets: [] })),
      upload: vi.fn().mockResolvedValue(mockSuccess({ asset: { key: '', url: '' } })),
      delete: vi.fn().mockResolvedValue(mockSuccess({ deleted: true })),
    },

    permissions: {
      get: vi.fn().mockResolvedValue(mockSuccess({ permissions: [] })),
      update: vi.fn().mockResolvedValue(mockSuccess({ permissions: [] })),
      searchUsers: vi.fn().mockResolvedValue(mockSuccess({ users: [] })),
      listGroups: vi.fn().mockResolvedValue(mockSuccess({ groups: [] })),
    },

    groups: {
      getInternal: vi.fn().mockResolvedValue(mockSuccess({ groups: [] })),
      updateInternal: vi.fn().mockResolvedValue(mockSuccess({})),
      searchExternal: vi.fn().mockResolvedValue(mockSuccess({ groups: [] })),
    },

    user: {
      whoami: vi.fn().mockResolvedValue(mockSuccess({ userId: 'mock-user', groups: [] })),
    },
  } as MockApiClient
}

// ========== Response Helpers ==========

/**
 * Create a successful API response
 */
export function mockSuccess<T>(data: T): ApiResponse<T> {
  return { ok: true, status: 200, data }
}

/**
 * Create an error API response
 */
export function mockError(status: number, error: string): ApiResponse<never> {
  return { ok: false, status, error }
}

/**
 * Create a 404 not found response
 */
export function mockNotFound(): ApiResponse<never> {
  return mockError(404, 'Not found')
}

/**
 * Create a 403 forbidden response
 */
export function mockForbidden(): ApiResponse<never> {
  return mockError(403, 'Forbidden')
}

// ========== Auto-Generated Response Factories ==========
// Generated by scripts/generate-client.ts - DO NOT EDIT MANUALLY

/**
 * Create a BranchListResponse for testing
 */
export function mockBranchListResponse(): BranchListResponse {
  return mockSuccess({ branches: [] })
}

/**
 * Create a BranchResponse for testing
 */
export function mockBranchResponse(): BranchResponse {
  return mockSuccess({
    branch: {
      name: 'test-branch',
      status: 'editing',
      access: {},
      createdBy: 'user-1',
      createdAt: '2024-01-01',
      updatedAt: '2024-01-01',
    },
  })
}

/**
 * Create a BranchDeleteResponse for testing
 */
export function mockBranchDeleteResponse(): BranchDeleteResponse {
  return mockSuccess({ deleted: true })
}

/**
 * Create a BranchMergeResponse for testing
 */
export function mockBranchMergeResponse(): BranchMergeResponse {
  return mockSuccess({ branch: { name: 'test-branch', status: 'archived' } })
}

/**
 * Create a CommentsResponse for testing
 */
export function mockCommentsResponse(): CommentsResponse {
  return mockSuccess({ threads: [] })
}

/**
 * Create a AddCommentResponse for testing
 */
export function mockAddCommentResponse(): AddCommentResponse {
  return mockSuccess({ threadId: 'mock-thread-id', commentId: 'mock-comment-id' })
}

/**
 * Create a ResolveCommentResponse for testing
 */
export function mockResolveCommentResponse(): ResolveCommentResponse {
  return mockSuccess({ resolved: true })
}

/**
 * Create a ContentReadResponse for testing
 */
export function mockContentReadResponse(): ContentReadResponse {
  return mockSuccess({ format: 'json', data: {} })
}

/**
 * Create a ContentWriteResponse for testing
 */
export function mockContentWriteResponse(): ContentWriteResponse {
  return mockSuccess({ format: 'json', data: {} })
}

/**
 * Create a ReferenceValidationResponse for testing
 */
export function mockReferenceValidationResponse(): ReferenceValidationResponse {
  return mockSuccess({ valid: true })
}

/**
 * Create a ReferenceOptionsResponse for testing
 */
export function mockReferenceOptionsResponse(): ReferenceOptionsResponse {
  return mockSuccess({ options: [] })
}

/**
 * Create a ResolveReferencesResponse for testing
 */
export function mockResolveReferencesResponse(): ResolveReferencesResponse {
  return mockSuccess({ resolved: {} })
}

/**
 * Create a EntriesResponse for testing
 */
export function mockEntriesResponse(): EntriesResponse {
  return mockSuccess({ collections: [], entries: [], pagination: { hasMore: false, limit: 50 } })
}

/**
 * Create a AssetsListResponse for testing
 */
export function mockAssetsListResponse(): AssetsListResponse {
  return mockSuccess({ assets: [] })
}

/**
 * Create a AssetUploadResponse for testing
 */
export function mockAssetUploadResponse(): AssetUploadResponse {
  return mockSuccess({ asset: { key: '', url: '' } })
}

/**
 * Create a AssetDeleteResponse for testing
 */
export function mockAssetDeleteResponse(): AssetDeleteResponse {
  return mockSuccess({ deleted: true })
}

/**
 * Create a PermissionsResponse for testing
 */
export function mockPermissionsResponse(): PermissionsResponse {
  return mockSuccess({ permissions: [] })
}

/**
 * Create a SearchUsersResponse for testing
 */
export function mockSearchUsersResponse(): SearchUsersResponse {
  return mockSuccess({ users: [] })
}

/**
 * Create a ListGroupsResponse for testing
 */
export function mockListGroupsResponse(): ListGroupsResponse {
  return mockSuccess({ groups: [] })
}

/**
 * Create a InternalGroupsResponse for testing
 */
export function mockInternalGroupsResponse(): InternalGroupsResponse {
  return mockSuccess({ groups: [] })
}

/**
 * Create a UpdateInternalGroupsResponse for testing
 */
export function mockUpdateInternalGroupsResponse(): UpdateInternalGroupsResponse {
  return mockSuccess({})
}

/**
 * Create a ExternalGroupsResponse for testing
 */
export function mockExternalGroupsResponse(): ExternalGroupsResponse {
  return mockSuccess({ groups: [] })
}

/**
 * Create a UserInfoResponse for testing
 */
export function mockUserInfoResponse(): UserInfoResponse {
  return mockSuccess({ userId: 'mock-user', groups: [] })
}
