/**
 * Mock API client for testing hooks and components.
 *
 * AUTO-GENERATED by scripts/generate-client.ts
 * Do not edit this file manually - changes will be overwritten.
 */

import { vi, type Mock } from 'vitest'
import type { CanopyApiClient } from '../client'
import type { ApiResponse } from '../types'
import { createLogicalPath, createPhysicalPath } from '../../paths'
import type { ContentId } from '../../paths'
import type { BranchDeleteResponse, BranchListResponse, BranchResponse, CreateBranchBody, UpdateBranchAccessBody } from '../branch'
import type { BranchMergeResponse } from '../branch-status'
import type { AddCommentBody, AddCommentResponse, CommentsResponse, ResolveCommentResponse } from '../comments'
import type { ContentReadResponse, ContentWriteResponse, ReferenceValidationResponse, RenameEntryBody, RenameEntryResponse, ValidateReferencesBody, WriteContentBody } from '../content'
import type { ReferenceOptionsResponse } from '../reference-options'
import type { ResolveReferencesBody, ResolveReferencesResponse } from '../resolve-references'
import type { DeleteEntryResponse, EntriesResponse } from '../entries'
import type { AssetDeleteResponse, AssetsListResponse, FinalizeAssetBody, FinalizeAssetResponse, PresignAssetBody, PresignAssetResponse } from '../assets'
import type { GetUserMetadataResponse, ListGroupsResponse, PermissionsResponse, SearchUsersResponse, UpdatePermissionsBody } from '../permissions'
import type { ExternalGroupsResponse, InternalGroupsResponse, UpdateInternalGroupsBody, UpdateInternalGroupsResponse } from '../groups'
import type { UserInfoResponse } from '../user'
import type { AddEntryTypeApiResponse, CreateCollectionApiResponse, DeleteCollectionApiResponse, GetCollectionApiResponse, GetSchemaApiResponse, InvalidateSchemaCacheApiResponse, RemoveEntryTypeApiResponse, UpdateCollectionApiResponse, UpdateEntryTypeApiResponse, UpdateOrderApiResponse, UpdateOrderBody } from '../schema'
import type { CreateCollectionInput, CreateEntryTypeInput, UpdateCollectionInput, UpdateEntryTypeInput } from '../../schema/schema-store-types'
import type { AdminDeleteTaskResponse, AdminRetryTaskResponse, AdminStatusResponse, AdminTasksResponse, BranchHealthResponse, PurgeBranchDirResponse, RepairBranchDirResponse, RepairContentDuplicatesResponse } from '../admin'

/**
 * Type utility to convert CanopyApiClient methods to Vitest mocks.
 */
export type MockApiClient = {
  [K in keyof CanopyApiClient]: CanopyApiClient[K] extends Record<string, any>
    ? {
        [M in keyof CanopyApiClient[K]]: CanopyApiClient[K][M] extends (...args: infer Args) => infer Return
          ? Mock<(...args: Args) => Return>
          : never
      }
    : never
}

/**
 * Create a mock API client with all methods as vi.fn().
 */
export function createMockApiClient(): MockApiClient {
  return {
  branches: {
    list: vi.fn().mockResolvedValue(mockSuccess({"branches":[]})),
    create: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"test-branch","status":"editing","access":{},"createdBy":"user-1","createdAt":"2024-01-01","updatedAt":"2024-01-01"}})),
    delete: vi.fn().mockResolvedValue(mockSuccess({"deleted":true})),
    updateAccess: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"test-branch","status":"editing","access":{},"createdBy":"user-1","createdAt":"2024-01-01","updatedAt":"2024-01-01"}})),
  },

  workflow: {
    withdraw: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"test-branch","status":"editing","access":{},"createdBy":"user-1","createdAt":"2024-01-01","updatedAt":"2024-01-01"}})),
    requestChanges: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"test-branch","status":"editing","access":{},"createdBy":"user-1","createdAt":"2024-01-01","updatedAt":"2024-01-01"}})),
    approve: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"test-branch","status":"approved","access":{},"createdBy":"user-1","createdAt":"2024-01-01","updatedAt":"2024-01-01"}})),
    markMerged: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"test-branch","status":"archived"}})),
    getStatus: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"test-branch","status":"editing","access":{},"createdBy":"user-1","createdAt":"2024-01-01","updatedAt":"2024-01-01"}})),
    submit: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"test-branch","status":"submitted","access":{},"createdBy":"user-1","createdAt":"2024-01-01","updatedAt":"2024-01-01"}})),
  },

  comments: {
    list: vi.fn().mockResolvedValue(mockSuccess({"threads":[]})),
    add: vi.fn().mockResolvedValue(mockSuccess({"threadId":"mock-thread-id","commentId":"mock-comment-id"})),
    resolve: vi.fn().mockResolvedValue(mockSuccess({"resolved":true})),
  },

  content: {
    read: vi.fn().mockResolvedValue(mockSuccess({"format":"json","data":{}})),
    write: vi.fn().mockResolvedValue(mockSuccess({"format":"json","data":{}})),
    validateReferences: vi.fn().mockResolvedValue(mockSuccess({"valid":true})),
    renameEntry: vi.fn().mockResolvedValue(mockSuccess({"newPath":"content/posts/new-slug"})),
    getReferenceOptions: vi.fn().mockResolvedValue(mockSuccess({"options":[]})),
    resolveReferences: vi.fn().mockResolvedValue(mockSuccess({"resolved":{}})),
  },

  entries: {
    list: vi.fn().mockResolvedValue(mockSuccess({"entries":[],"pagination":{"hasMore":false,"limit":50}})),
    delete: vi.fn().mockResolvedValue(mockSuccess({"deleted":true})),
  },

  assets: {
    presign: vi.fn().mockResolvedValue(mockSuccess({"upload":{"mode":"proxied","stagingKey":"asset-staging/mock","maxBytes":52428800}})),
    finalize: vi.fn().mockResolvedValue(mockSuccess({"asset":{"hash32":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","filename":"sample.png","slug":"sample","ext":"png","mime":"image/png","size":1024,"width":100,"height":100,"kind":"raster","uploadedAt":"2024-01-01T00:00:00.000Z","src":"/assets/t/orig/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/sample.png"}})),
    uploadProxied: vi.fn().mockResolvedValue(mockSuccess({"asset":{"hash32":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","filename":"sample.png","slug":"sample","ext":"png","mime":"image/png","size":1024,"width":100,"height":100,"kind":"raster","uploadedAt":"2024-01-01T00:00:00.000Z","src":"/assets/t/orig/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/sample.png"}})),
    list: vi.fn().mockResolvedValue(mockSuccess({"assets":[]})),
    delete: vi.fn().mockResolvedValue(mockSuccess({"deleted":true})),
  },

  permissions: {
    get: vi.fn().mockResolvedValue(mockSuccess({"permissions":[],"version":0})),
    update: vi.fn().mockResolvedValue(mockSuccess({"permissions":[]})),
    searchUsers: vi.fn().mockResolvedValue(mockSuccess({"users":[]})),
    listGroups: vi.fn().mockResolvedValue(mockSuccess({"groups":[]})),
    getUserMetadata: vi.fn().mockResolvedValue(mockSuccess({"user":null})),
  },

  groups: {
    getInternal: vi.fn().mockResolvedValue(mockSuccess({"groups":[],"version":0})),
    updateInternal: vi.fn().mockResolvedValue(mockSuccess({})),
    searchExternal: vi.fn().mockResolvedValue(mockSuccess({"groups":[]})),
  },

  user: {
    whoami: vi.fn().mockResolvedValue(mockSuccess({"userId":"mock-user","groups":[]})),
  },

  schema: {
    get: vi.fn().mockResolvedValue(mockSuccess({"flatSchema":[],"entrySchemas":{}})),
    getCollection: vi.fn().mockResolvedValue(mockSuccess({"collection":null})),
    createCollection: vi.fn().mockResolvedValue(mockSuccess({"collectionPath":"","contentId":""})),
    updateCollection: vi.fn().mockResolvedValue(mockSuccess({"success":true})),
    deleteCollection: vi.fn().mockResolvedValue(mockSuccess({"success":true})),
    addEntryType: vi.fn().mockResolvedValue(mockSuccess({"success":true})),
    updateEntryType: vi.fn().mockResolvedValue(mockSuccess({"success":true})),
    removeEntryType: vi.fn().mockResolvedValue(mockSuccess({"success":true})),
    updateOrder: vi.fn().mockResolvedValue(mockSuccess({"success":true})),
    invalidateSchemaCache: vi.fn().mockResolvedValue(mockSuccess({"success":true,"message":"Cache invalidated"})),
  },

  admin: {
    branchHealth: vi.fn().mockResolvedValue(mockSuccess({"entries":[],"generatedAt":"2024-01-01T00:00:00.000Z"})),
    purgeBranchDir: vi.fn().mockResolvedValue(mockSuccess({"trashedAs":".trash-example-branch-20240101T000000Z"})),
    repairBranchDir: vi.fn().mockResolvedValue(mockSuccess({"branch":{"name":"example-branch","status":"editing","access":{},"createdBy":"admin","createdAt":"2024-01-01T00:00:00.000Z","updatedAt":"2024-01-01T00:00:00.000Z"},"archivedAs":"branch.json.corrupt-20240101T000000Z","reset":{"status":"editing","access":{},"createdBy":"admin"}})),
    repairContentDuplicates: vi.fn().mockResolvedValue(mockSuccess({"resolved":[{"id":"a1b2c3d4e5f6","keptPath":"content/posts/dune.a1b2c3d4e5f6.json","archivedAs":[".duplicate-content-id.20240101T000000Z.post.dune-old.a1b2c3d4e5f6.json"]}]})),
    status: vi.fn().mockResolvedValue(mockSuccess({"generatedAt":"2024-01-01T00:00:00.000Z","mode":"prod","queue":{"pending":0,"processing":0,"completed":0,"failed":0,"corrupt":0},"worker":{"state":"absent"},"workerStatus":null})),
    listTasks: vi.fn().mockResolvedValue(mockSuccess({"tasks":[]})),
    retryTask: vi.fn().mockResolvedValue(mockSuccess({"newTaskId":"00000000-0000-0000-0000-000000000000"})),
    deleteTask: vi.fn().mockResolvedValue(mockSuccess({"deleted":true})),
  },
  } as MockApiClient
}

// ========== Response Helpers ==========

/**
 * Create a successful API response
 */
export function mockSuccess<T>(data: T): ApiResponse<T> {
  return { ok: true, status: 200, data }
}

/**
 * Create an error API response
 */
export function mockError(status: number, error: string): ApiResponse<never> {
  return { ok: false, status, error }
}

/**
 * Create a 404 not found response
 */
export function mockNotFound(): ApiResponse<never> {
  return mockError(404, 'Not found')
}

/**
 * Create a 403 forbidden response
 */
export function mockForbidden(): ApiResponse<never> {
  return mockError(403, 'Forbidden')
}

// ========== Auto-Generated Response Factories ==========
// Generated by scripts/generate-client.ts - DO NOT EDIT MANUALLY

/**
 * Create a BranchListResponse for testing
 */
export function mockBranchListResponse(): BranchListResponse {
  return mockSuccess({"branches":[]})
}

/**
 * Create a BranchResponse for testing
 */
export function mockBranchResponse(): BranchResponse {
  return mockSuccess({"branch":{"name":"test-branch","status":"editing","access":{},"createdBy":"user-1","createdAt":"2024-01-01","updatedAt":"2024-01-01"}})
}

/**
 * Create a BranchDeleteResponse for testing
 */
export function mockBranchDeleteResponse(): BranchDeleteResponse {
  return mockSuccess({"deleted":true})
}

/**
 * Create a BranchMergeResponse for testing
 */
export function mockBranchMergeResponse(): BranchMergeResponse {
  return mockSuccess({"branch":{"name":"test-branch","status":"archived"}})
}

/**
 * Create a CommentsResponse for testing
 */
export function mockCommentsResponse(): CommentsResponse {
  return mockSuccess({"threads":[]})
}

/**
 * Create a AddCommentResponse for testing
 */
export function mockAddCommentResponse(): AddCommentResponse {
  return mockSuccess({"threadId":"mock-thread-id","commentId":"mock-comment-id"})
}

/**
 * Create a ResolveCommentResponse for testing
 */
export function mockResolveCommentResponse(): ResolveCommentResponse {
  return mockSuccess({"resolved":true})
}

/**
 * Create a ContentReadResponse for testing
 */
export function mockContentReadResponse(): ContentReadResponse {
  return mockSuccess({"format":"json","data":{}})
}

/**
 * Create a ContentWriteResponse for testing
 */
export function mockContentWriteResponse(): ContentWriteResponse {
  return mockSuccess({"format":"json","data":{}})
}

/**
 * Create a ReferenceValidationResponse for testing
 */
export function mockReferenceValidationResponse(): ReferenceValidationResponse {
  return mockSuccess({"valid":true})
}

/**
 * Create a RenameEntryResponse for testing
 */
export function mockRenameEntryResponse(): RenameEntryResponse {
  return mockSuccess({"newPath":"content/posts/new-slug"})
}

/**
 * Create a ReferenceOptionsResponse for testing
 */
export function mockReferenceOptionsResponse(): ReferenceOptionsResponse {
  return mockSuccess({"options":[]})
}

/**
 * Create a ResolveReferencesResponse for testing
 */
export function mockResolveReferencesResponse(): ResolveReferencesResponse {
  return mockSuccess({"resolved":{}})
}

/**
 * Create a EntriesResponse for testing
 */
export function mockEntriesResponse(): EntriesResponse {
  return mockSuccess({"entries":[],"pagination":{"hasMore":false,"limit":50}})
}

/**
 * Create a DeleteEntryResponse for testing
 */
export function mockDeleteEntryResponse(): DeleteEntryResponse {
  return mockSuccess({"deleted":true})
}

/**
 * Create a PresignAssetResponse for testing
 */
export function mockPresignAssetResponse(): PresignAssetResponse {
  return mockSuccess({"upload":{"mode":"proxied","stagingKey":"asset-staging/mock","maxBytes":52428800}})
}

/**
 * Create a FinalizeAssetResponse for testing
 */
export function mockFinalizeAssetResponse(): FinalizeAssetResponse {
  return mockSuccess({"asset":{"hash32":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","filename":"sample.png","slug":"sample","ext":"png","mime":"image/png","size":1024,"width":100,"height":100,"kind":"raster","uploadedAt":"2024-01-01T00:00:00.000Z","src":"/assets/t/orig/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/sample.png"}})
}

/**
 * Create a AssetsListResponse for testing
 */
export function mockAssetsListResponse(): AssetsListResponse {
  return mockSuccess({"assets":[]})
}

/**
 * Create a AssetDeleteResponse for testing
 */
export function mockAssetDeleteResponse(): AssetDeleteResponse {
  return mockSuccess({"deleted":true})
}

/**
 * Create a PermissionsResponse for testing
 */
export function mockPermissionsResponse(): PermissionsResponse {
  return mockSuccess({"permissions":[],"version":0})
}

/**
 * Create a SearchUsersResponse for testing
 */
export function mockSearchUsersResponse(): SearchUsersResponse {
  return mockSuccess({"users":[]})
}

/**
 * Create a ListGroupsResponse for testing
 */
export function mockListGroupsResponse(): ListGroupsResponse {
  return mockSuccess({"groups":[]})
}

/**
 * Create a GetUserMetadataResponse for testing
 */
export function mockGetUserMetadataResponse(): GetUserMetadataResponse {
  return mockSuccess({"user":null})
}

/**
 * Create a InternalGroupsResponse for testing
 */
export function mockInternalGroupsResponse(): InternalGroupsResponse {
  return mockSuccess({"groups":[],"version":0})
}

/**
 * Create a UpdateInternalGroupsResponse for testing
 */
export function mockUpdateInternalGroupsResponse(): UpdateInternalGroupsResponse {
  return mockSuccess({})
}

/**
 * Create a ExternalGroupsResponse for testing
 */
export function mockExternalGroupsResponse(): ExternalGroupsResponse {
  return mockSuccess({"groups":[]})
}

/**
 * Create a UserInfoResponse for testing
 */
export function mockUserInfoResponse(): UserInfoResponse {
  return mockSuccess({"userId":"mock-user","groups":[]})
}

/**
 * Create a GetSchemaApiResponse for testing
 */
export function mockGetSchemaApiResponse(): GetSchemaApiResponse {
  return mockSuccess({"flatSchema":[],"entrySchemas":{}})
}

/**
 * Create a GetCollectionApiResponse for testing
 */
export function mockGetCollectionApiResponse(): GetCollectionApiResponse {
  return mockSuccess({"collection":null})
}

/**
 * Create a CreateCollectionApiResponse for testing
 */
export function mockCreateCollectionApiResponse(): CreateCollectionApiResponse {
  return mockSuccess({"collectionPath":createLogicalPath(""),"contentId":"" as ContentId})
}

/**
 * Create a UpdateCollectionApiResponse for testing
 */
export function mockUpdateCollectionApiResponse(): UpdateCollectionApiResponse {
  return mockSuccess({"success":true})
}

/**
 * Create a DeleteCollectionApiResponse for testing
 */
export function mockDeleteCollectionApiResponse(): DeleteCollectionApiResponse {
  return mockSuccess({"success":true})
}

/**
 * Create a AddEntryTypeApiResponse for testing
 */
export function mockAddEntryTypeApiResponse(): AddEntryTypeApiResponse {
  return mockSuccess({"success":true})
}

/**
 * Create a UpdateEntryTypeApiResponse for testing
 */
export function mockUpdateEntryTypeApiResponse(): UpdateEntryTypeApiResponse {
  return mockSuccess({"success":true})
}

/**
 * Create a RemoveEntryTypeApiResponse for testing
 */
export function mockRemoveEntryTypeApiResponse(): RemoveEntryTypeApiResponse {
  return mockSuccess({"success":true})
}

/**
 * Create a UpdateOrderApiResponse for testing
 */
export function mockUpdateOrderApiResponse(): UpdateOrderApiResponse {
  return mockSuccess({"success":true})
}

/**
 * Create a InvalidateSchemaCacheApiResponse for testing
 */
export function mockInvalidateSchemaCacheApiResponse(): InvalidateSchemaCacheApiResponse {
  return mockSuccess({"success":true,"message":"Cache invalidated"})
}

/**
 * Create a BranchHealthResponse for testing
 */
export function mockBranchHealthResponse(): BranchHealthResponse {
  return mockSuccess({"entries":[],"generatedAt":"2024-01-01T00:00:00.000Z"})
}

/**
 * Create a PurgeBranchDirResponse for testing
 */
export function mockPurgeBranchDirResponse(): PurgeBranchDirResponse {
  return mockSuccess({"trashedAs":".trash-example-branch-20240101T000000Z"})
}

/**
 * Create a RepairBranchDirResponse for testing
 */
export function mockRepairBranchDirResponse(): RepairBranchDirResponse {
  return mockSuccess({"branch":{"name":"example-branch","status":"editing","access":{},"createdBy":"admin","createdAt":"2024-01-01T00:00:00.000Z","updatedAt":"2024-01-01T00:00:00.000Z"},"archivedAs":"branch.json.corrupt-20240101T000000Z","reset":{"status":"editing","access":{},"createdBy":"admin"}})
}

/**
 * Create a RepairContentDuplicatesResponse for testing
 */
export function mockRepairContentDuplicatesResponse(): RepairContentDuplicatesResponse {
  return mockSuccess({"resolved":[{"id":"a1b2c3d4e5f6","keptPath":"content/posts/dune.a1b2c3d4e5f6.json","archivedAs":[".duplicate-content-id.20240101T000000Z.post.dune-old.a1b2c3d4e5f6.json"]}]})
}

/**
 * Create a AdminStatusResponse for testing
 */
export function mockAdminStatusResponse(): AdminStatusResponse {
  return mockSuccess({"generatedAt":"2024-01-01T00:00:00.000Z","mode":"prod","queue":{"pending":0,"processing":0,"completed":0,"failed":0,"corrupt":0},"worker":{"state":"absent"},"workerStatus":null})
}

/**
 * Create a AdminTasksResponse for testing
 */
export function mockAdminTasksResponse(): AdminTasksResponse {
  return mockSuccess({"tasks":[]})
}

/**
 * Create a AdminRetryTaskResponse for testing
 */
export function mockAdminRetryTaskResponse(): AdminRetryTaskResponse {
  return mockSuccess({"newTaskId":"00000000-0000-0000-0000-000000000000"})
}

/**
 * Create a AdminDeleteTaskResponse for testing
 */
export function mockAdminDeleteTaskResponse(): AdminDeleteTaskResponse {
  return mockSuccess({"deleted":true})
}
