/**
 * Mock API client for testing hooks and components.
 *
 * AUTO-GENERATED by scripts/generate-client.ts
 * Do not edit this file manually - changes will be overwritten.
 */

import { vi, type Mock } from 'vitest'
import type { CanopyApiClient } from '../client'
import type { ApiResponse } from '../types'
import { createLogicalPath } from '../../paths'
import type { ContentId } from '../../paths'
import type {
  BranchDeleteResponse,
  BranchListResponse,
  BranchResponse,
  CreateBranchBody,
  UpdateBranchAccessBody,
} from '../branch'
import type { BranchMergeResponse } from '../branch-status'
import type { RequestChangesBody } from '../branch-review'
import type {
  AddCommentBody,
  AddCommentResponse,
  CommentsResponse,
  ResolveCommentResponse,
} from '../comments'
import type {
  ContentReadResponse,
  ContentWriteResponse,
  ReferenceValidationResponse,
  RenameEntryBody,
  RenameEntryResponse,
  ValidateReferencesBody,
  WriteContentBody,
} from '../content'
import type { ReferenceOptionsResponse } from '../reference-options'
import type { ResolveReferencesBody, ResolveReferencesResponse } from '../resolve-references'
import type { DeleteEntryResponse, EntriesResponse } from '../entries'
import type {
  AssetDeleteResponse,
  AssetUploadResponse,
  AssetsListResponse,
  UploadAssetBody,
} from '../assets'
import type {
  GetUserMetadataResponse,
  ListGroupsResponse,
  PermissionsResponse,
  SearchUsersResponse,
  UpdatePermissionsBody,
} from '../permissions'
import type {
  ExternalGroupsResponse,
  InternalGroupsResponse,
  UpdateInternalGroupsBody,
  UpdateInternalGroupsResponse,
} from '../groups'
import type { UserInfoResponse } from '../user'
import type {
  AddEntryTypeApiResponse,
  CreateCollectionApiResponse,
  DeleteCollectionApiResponse,
  GetCollectionApiResponse,
  GetSchemaApiResponse,
  InvalidateSchemaCacheApiResponse,
  RemoveEntryTypeApiResponse,
  UpdateCollectionApiResponse,
  UpdateEntryTypeApiResponse,
  UpdateOrderApiResponse,
  UpdateOrderBody,
} from '../schema'
import type {
  CreateCollectionInput,
  CreateEntryTypeInput,
  UpdateCollectionInput,
  UpdateEntryTypeInput,
} from '../../schema/schema-store-types'

/**
 * Type utility to convert CanopyApiClient methods to Vitest mocks.
 */
export type MockApiClient = {
  [K in keyof CanopyApiClient]: CanopyApiClient[K] extends Record<string, any>
    ? {
        [M in keyof CanopyApiClient[K]]: CanopyApiClient[K][M] extends (
          ...args: infer Args
        ) => infer Return
          ? Mock<Args, Return>
          : never
      }
    : never
}

/**
 * Create a mock API client with all methods as vi.fn().
 */
export function createMockApiClient(): MockApiClient {
  return {
    branches: {
      list: vi.fn().mockResolvedValue(mockSuccess({ branches: [] })),
      create: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      delete: vi.fn().mockResolvedValue(mockSuccess({ deleted: true })),
      updateAccess: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
    },

    workflow: {
      withdraw: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      requestChanges: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      approve: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'approved',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      markMerged: vi
        .fn()
        .mockResolvedValue(mockSuccess({ branch: { name: 'test-branch', status: 'archived' } })),
      getStatus: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'editing',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
      submit: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({
            branch: {
              name: 'test-branch',
              status: 'submitted',
              access: {},
              createdBy: 'user-1',
              createdAt: '2024-01-01',
              updatedAt: '2024-01-01',
            },
          }),
        ),
    },

    comments: {
      list: vi.fn().mockResolvedValue(mockSuccess({ threads: [] })),
      add: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({ threadId: 'mock-thread-id', commentId: 'mock-comment-id' }),
        ),
      resolve: vi.fn().mockResolvedValue(mockSuccess({ resolved: true })),
    },

    content: {
      read: vi.fn().mockResolvedValue(mockSuccess({ format: 'json', data: {} })),
      write: vi.fn().mockResolvedValue(mockSuccess({ format: 'json', data: {} })),
      validateReferences: vi.fn().mockResolvedValue(mockSuccess({ valid: true })),
      renameEntry: vi.fn().mockResolvedValue(mockSuccess({ newPath: 'content/posts/new-slug' })),
      getReferenceOptions: vi.fn().mockResolvedValue(mockSuccess({ options: [] })),
      resolveReferences: vi.fn().mockResolvedValue(mockSuccess({ resolved: {} })),
    },

    entries: {
      list: vi
        .fn()
        .mockResolvedValue(
          mockSuccess({ collections: [], entries: [], pagination: { hasMore: false, limit: 50 } }),
        ),
      delete: vi.fn().mockResolvedValue(mockSuccess({ deleted: true })),
    },

    assets: {
      list: vi.fn().mockResolvedValue(mockSuccess({ assets: [] })),
      upload: vi.fn().mockResolvedValue(mockSuccess({ asset: { key: '', url: '' } })),
      delete: vi.fn().mockResolvedValue(mockSuccess({ deleted: true })),
    },

    permissions: {
      get: vi.fn().mockResolvedValue(mockSuccess({ permissions: [] })),
      update: vi.fn().mockResolvedValue(mockSuccess({ permissions: [] })),
      searchUsers: vi.fn().mockResolvedValue(mockSuccess({ users: [] })),
      listGroups: vi.fn().mockResolvedValue(mockSuccess({ groups: [] })),
      getUserMetadata: vi.fn().mockResolvedValue(mockSuccess({ user: null })),
    },

    groups: {
      getInternal: vi.fn().mockResolvedValue(mockSuccess({ groups: [] })),
      updateInternal: vi.fn().mockResolvedValue(mockSuccess({})),
      searchExternal: vi.fn().mockResolvedValue(mockSuccess({ groups: [] })),
    },

    user: {
      whoami: vi.fn().mockResolvedValue(mockSuccess({ userId: 'mock-user', groups: [] })),
    },

    schema: {
      get: vi.fn().mockResolvedValue(mockSuccess({ schema: {}, flatSchema: [], entrySchemas: {} })),
      getCollection: vi.fn().mockResolvedValue(mockSuccess({ collection: null })),
      createCollection: vi
        .fn()
        .mockResolvedValue(mockSuccess({ collectionPath: '', contentId: '' })),
      updateCollection: vi.fn().mockResolvedValue(mockSuccess({ success: true })),
      deleteCollection: vi.fn().mockResolvedValue(mockSuccess({ success: true })),
      addEntryType: vi.fn().mockResolvedValue(mockSuccess({ success: true })),
      updateEntryType: vi.fn().mockResolvedValue(mockSuccess({ success: true })),
      removeEntryType: vi.fn().mockResolvedValue(mockSuccess({ success: true })),
      updateOrder: vi.fn().mockResolvedValue(mockSuccess({ success: true })),
      invalidateSchemaCache: vi
        .fn()
        .mockResolvedValue(mockSuccess({ success: true, message: 'Cache invalidated' })),
    },
  } as MockApiClient
}

// ========== Response Helpers ==========

/**
 * Create a successful API response
 */
export function mockSuccess<T>(data: T): ApiResponse<T> {
  return { ok: true, status: 200, data }
}

/**
 * Create an error API response
 */
export function mockError(status: number, error: string): ApiResponse<never> {
  return { ok: false, status, error }
}

/**
 * Create a 404 not found response
 */
export function mockNotFound(): ApiResponse<never> {
  return mockError(404, 'Not found')
}

/**
 * Create a 403 forbidden response
 */
export function mockForbidden(): ApiResponse<never> {
  return mockError(403, 'Forbidden')
}

// ========== Auto-Generated Response Factories ==========
// Generated by scripts/generate-client.ts - DO NOT EDIT MANUALLY

/**
 * Create a BranchListResponse for testing
 */
export function mockBranchListResponse(): BranchListResponse {
  return mockSuccess({ branches: [] })
}

/**
 * Create a BranchResponse for testing
 */
export function mockBranchResponse(): BranchResponse {
  return mockSuccess({
    branch: {
      name: 'test-branch',
      status: 'editing',
      access: {},
      createdBy: 'user-1',
      createdAt: '2024-01-01',
      updatedAt: '2024-01-01',
    },
  })
}

/**
 * Create a BranchDeleteResponse for testing
 */
export function mockBranchDeleteResponse(): BranchDeleteResponse {
  return mockSuccess({ deleted: true })
}

/**
 * Create a BranchMergeResponse for testing
 */
export function mockBranchMergeResponse(): BranchMergeResponse {
  return mockSuccess({ branch: { name: 'test-branch', status: 'archived' } })
}

/**
 * Create a CommentsResponse for testing
 */
export function mockCommentsResponse(): CommentsResponse {
  return mockSuccess({ threads: [] })
}

/**
 * Create a AddCommentResponse for testing
 */
export function mockAddCommentResponse(): AddCommentResponse {
  return mockSuccess({ threadId: 'mock-thread-id', commentId: 'mock-comment-id' })
}

/**
 * Create a ResolveCommentResponse for testing
 */
export function mockResolveCommentResponse(): ResolveCommentResponse {
  return mockSuccess({ resolved: true })
}

/**
 * Create a ContentReadResponse for testing
 */
export function mockContentReadResponse(): ContentReadResponse {
  return mockSuccess({ format: 'json', data: {} })
}

/**
 * Create a ContentWriteResponse for testing
 */
export function mockContentWriteResponse(): ContentWriteResponse {
  return mockSuccess({ format: 'json', data: {} })
}

/**
 * Create a ReferenceValidationResponse for testing
 */
export function mockReferenceValidationResponse(): ReferenceValidationResponse {
  return mockSuccess({ valid: true })
}

/**
 * Create a RenameEntryResponse for testing
 */
export function mockRenameEntryResponse(): RenameEntryResponse {
  return mockSuccess({ newPath: 'content/posts/new-slug' })
}

/**
 * Create a ReferenceOptionsResponse for testing
 */
export function mockReferenceOptionsResponse(): ReferenceOptionsResponse {
  return mockSuccess({ options: [] })
}

/**
 * Create a ResolveReferencesResponse for testing
 */
export function mockResolveReferencesResponse(): ResolveReferencesResponse {
  return mockSuccess({ resolved: {} })
}

/**
 * Create a EntriesResponse for testing
 */
export function mockEntriesResponse(): EntriesResponse {
  return mockSuccess({ collections: [], entries: [], pagination: { hasMore: false, limit: 50 } })
}

/**
 * Create a DeleteEntryResponse for testing
 */
export function mockDeleteEntryResponse(): DeleteEntryResponse {
  return mockSuccess({ deleted: true })
}

/**
 * Create a AssetsListResponse for testing
 */
export function mockAssetsListResponse(): AssetsListResponse {
  return mockSuccess({ assets: [] })
}

/**
 * Create a AssetUploadResponse for testing
 */
export function mockAssetUploadResponse(): AssetUploadResponse {
  return mockSuccess({ asset: { key: '', url: '' } })
}

/**
 * Create a AssetDeleteResponse for testing
 */
export function mockAssetDeleteResponse(): AssetDeleteResponse {
  return mockSuccess({ deleted: true })
}

/**
 * Create a PermissionsResponse for testing
 */
export function mockPermissionsResponse(): PermissionsResponse {
  return mockSuccess({ permissions: [] })
}

/**
 * Create a SearchUsersResponse for testing
 */
export function mockSearchUsersResponse(): SearchUsersResponse {
  return mockSuccess({ users: [] })
}

/**
 * Create a ListGroupsResponse for testing
 */
export function mockListGroupsResponse(): ListGroupsResponse {
  return mockSuccess({ groups: [] })
}

/**
 * Create a GetUserMetadataResponse for testing
 */
export function mockGetUserMetadataResponse(): GetUserMetadataResponse {
  return mockSuccess({ user: null })
}

/**
 * Create a InternalGroupsResponse for testing
 */
export function mockInternalGroupsResponse(): InternalGroupsResponse {
  return mockSuccess({ groups: [] })
}

/**
 * Create a UpdateInternalGroupsResponse for testing
 */
export function mockUpdateInternalGroupsResponse(): UpdateInternalGroupsResponse {
  return mockSuccess({})
}

/**
 * Create a ExternalGroupsResponse for testing
 */
export function mockExternalGroupsResponse(): ExternalGroupsResponse {
  return mockSuccess({ groups: [] })
}

/**
 * Create a UserInfoResponse for testing
 */
export function mockUserInfoResponse(): UserInfoResponse {
  return mockSuccess({ userId: 'mock-user', groups: [] })
}

/**
 * Create a GetSchemaApiResponse for testing
 */
export function mockGetSchemaApiResponse(): GetSchemaApiResponse {
  return mockSuccess({ schema: {}, flatSchema: [], entrySchemas: {} })
}

/**
 * Create a GetCollectionApiResponse for testing
 */
export function mockGetCollectionApiResponse(): GetCollectionApiResponse {
  return mockSuccess({ collection: null })
}

/**
 * Create a CreateCollectionApiResponse for testing
 */
export function mockCreateCollectionApiResponse(): CreateCollectionApiResponse {
  return mockSuccess({ collectionPath: createLogicalPath(''), contentId: '' as ContentId })
}

/**
 * Create a UpdateCollectionApiResponse for testing
 */
export function mockUpdateCollectionApiResponse(): UpdateCollectionApiResponse {
  return mockSuccess({ success: true })
}

/**
 * Create a DeleteCollectionApiResponse for testing
 */
export function mockDeleteCollectionApiResponse(): DeleteCollectionApiResponse {
  return mockSuccess({ success: true })
}

/**
 * Create a AddEntryTypeApiResponse for testing
 */
export function mockAddEntryTypeApiResponse(): AddEntryTypeApiResponse {
  return mockSuccess({ success: true })
}

/**
 * Create a UpdateEntryTypeApiResponse for testing
 */
export function mockUpdateEntryTypeApiResponse(): UpdateEntryTypeApiResponse {
  return mockSuccess({ success: true })
}

/**
 * Create a RemoveEntryTypeApiResponse for testing
 */
export function mockRemoveEntryTypeApiResponse(): RemoveEntryTypeApiResponse {
  return mockSuccess({ success: true })
}

/**
 * Create a UpdateOrderApiResponse for testing
 */
export function mockUpdateOrderApiResponse(): UpdateOrderApiResponse {
  return mockSuccess({ success: true })
}

/**
 * Create a InvalidateSchemaCacheApiResponse for testing
 */
export function mockInvalidateSchemaCacheApiResponse(): InvalidateSchemaCacheApiResponse {
  return mockSuccess({ success: true, message: 'Cache invalidated' })
}
