// Generated by scripts/bump-version.mjs, its only writer. The package builds with plain
// tsc (rootDir: src), so src/ cannot import ../package.json; version.test.ts keeps the two equal.
export const CANOPYCMS_VERSION = '0.0.67'
