/**
 * Typed API client for CanopyCMS: one method per endpoint, each returning that
 * endpoint's ApiResponse.
 *
 * AUTO-GENERATED by scripts/generate-client.ts; do not edit this file manually
 * (changes will be overwritten), edit the generator's templates instead.
 */

import { computeContentSha256Hex } from './request-body-hash'
import type { ApiResponse } from './types'
import { readTrailingSlashEnv, withTrailingSlash } from '../utils/url-prefix'

import type { BranchDeleteResponse, BranchListItemResponse, BranchListResponse, BranchResponse, CreateBranchBody, UpdateBranchAccessBody } from './branch'
import type { BranchMergeResponse } from './branch-status'
import type { AddCommentBody, AddCommentResponse, CommentsResponse, ResolveCommentResponse } from './comments'
import type { ContentReadResponse, ContentWriteResponse, ReferenceValidationResponse, RenameEntryBody, RenameEntryResponse, ValidateReferencesBody, WriteContentBody } from './content'
import type { ReferenceOptionsResponse } from './reference-options'
import type { ResolveReferencesBody, ResolveReferencesResponse } from './resolve-references'
import type { DeleteEntryResponse, EntriesResponse } from './entries'
import type { AssetDeleteResponse, AssetsListResponse, FinalizeAssetBody, FinalizeAssetResponse, PresignAssetBody, PresignAssetResponse } from './assets'
import type { GetUserMetadataResponse, ListGroupsResponse, PermissionsResponse, SearchUsersResponse, UpdatePermissionsBody } from './permissions'
import type { ExternalGroupsResponse, InternalGroupsResponse, UpdateInternalGroupsBody, UpdateInternalGroupsResponse } from './groups'
import type { UserInfoResponse } from './user'
import type { AddEntryTypeApiResponse, CreateCollectionApiResponse, DeleteCollectionApiResponse, GetCollectionApiResponse, GetSchemaApiResponse, InvalidateSchemaCacheApiResponse, RemoveEntryTypeApiResponse, UpdateCollectionApiResponse, UpdateEntryTypeApiResponse, UpdateOrderApiResponse, UpdateOrderBody } from './schema'
import type { CreateCollectionInput, CreateEntryTypeInput, UpdateCollectionInput, UpdateEntryTypeInput } from './../schema/schema-store-types'
import type { AdminDeleteTaskResponse, AdminRetryTaskResponse, AdminStatusResponse, AdminTasksResponse, BranchHealthResponse, PurgeBranchDirResponse, RepairBranchDirResponse, RepairContentDuplicatesResponse } from './admin'

/** Options for {@link createApiClient}. */
export interface ApiClientOptions {
  /** Base URL for API requests. Defaults to '/api/canopycms'. */
  baseUrl?: string
  /** Custom fetch implementation, e.g. a mock in tests. */
  fetch?: typeof fetch
  /**
   * End request paths with `/` (by `withTrailingSlash`'s rule), matching a Next host built with
   * `trailingSlash: true`. Defaults to the value `withCanopy` inlines at build time (see
   * `readTrailingSlashEnv`), else false.
   */
  trailingSlash?: boolean

  /**
   * Called whenever a response comes back 401: the credential is no longer accepted. A
   * notification, not a retry; the editor's auth gate uses it to show sign-in.
   */
  onUnauthorized?: () => void
}

/**
 * Typed client for the CanopyCMS API: one method per endpoint, grouped by namespace, each
 * returning that endpoint's ApiResponse.
 *
 * @example
 * ```ts
 * const branches = await createApiClient().branches.list()
 * if (branches.ok) console.log(branches.data.branches)
 * ```
 */
export class CanopyApiClient {
  private baseUrl: string
  private fetchFn: typeof fetch
  private trailingSlash: boolean
  private onUnauthorized: (() => void) | undefined

  readonly branches = {
    /** GET /branches */
    list: (): Promise<BranchListResponse> => {
      return this.request('GET', '/branches')
    },

    /** POST /branches */
    create: (body: CreateBranchBody): Promise<BranchListItemResponse> => {
      return this.request('POST', '/branches', body)
    },

    /** DELETE /:branch */
    delete: (params: Record<string, string>): Promise<BranchDeleteResponse> => {
      return this.request('DELETE', this.buildPath('/:branch', params))
    },

    /** PATCH /:branch/access */
    updateAccess: (params: Record<string, string>, body: UpdateBranchAccessBody): Promise<BranchResponse> => {
      return this.request('PATCH', this.buildPath('/:branch/access', params), body)
    },
  }

  readonly workflow = {
    /** POST /:branch/withdraw */
    withdraw: (params: Record<string, string>): Promise<BranchListItemResponse> => {
      return this.request('POST', this.buildPath('/:branch/withdraw', params))
    },

    /** POST /:branch/request-changes */
    requestChanges: (params: Record<string, string>): Promise<BranchListItemResponse> => {
      return this.request('POST', this.buildPath('/:branch/request-changes', params))
    },

    /** POST /:branch/approve */
    approve: (params: Record<string, string>): Promise<BranchListItemResponse> => {
      return this.request('POST', this.buildPath('/:branch/approve', params))
    },

    /** POST /:branch/mark-merged */
    markMerged: (params: Record<string, string>): Promise<BranchMergeResponse> => {
      return this.request('POST', this.buildPath('/:branch/mark-merged', params))
    },

    /** GET /:branch/status */
    getStatus: (params: Record<string, string>): Promise<BranchResponse> => {
      return this.request('GET', this.buildPath('/:branch/status', params))
    },

    /** POST /:branch/submit */
    submit: (params: Record<string, string>): Promise<BranchListItemResponse> => {
      return this.request('POST', this.buildPath('/:branch/submit', params))
    },
  }

  readonly comments = {
    /** GET /:branch/comments */
    list: (params: Record<string, string>): Promise<CommentsResponse> => {
      return this.request('GET', this.buildPath('/:branch/comments', params))
    },

    /** POST /:branch/comments */
    add: (params: Record<string, string>, body: AddCommentBody): Promise<AddCommentResponse> => {
      return this.request('POST', this.buildPath('/:branch/comments', params), body)
    },

    /** POST /:branch/comments/:threadId/resolve */
    resolve: (params: Record<string, string>): Promise<ResolveCommentResponse> => {
      return this.request('POST', this.buildPath('/:branch/comments/:threadId/resolve', params))
    },
  }

  readonly content = {
    /** GET /:branch/content/...path */
    read: (params: Record<string, string>): Promise<ContentReadResponse> => {
      return this.request('GET', this.buildPath('/:branch/content/...path', params))
    },

    /** PUT /:branch/content/...path */
    write: (params: Record<string, string>, body: WriteContentBody): Promise<ContentWriteResponse> => {
      return this.request('PUT', this.buildPath('/:branch/content/...path', params), body)
    },

    /** POST /:branch/validate-references/...path */
    validateReferences: (params: Record<string, string>, body: ValidateReferencesBody): Promise<ReferenceValidationResponse> => {
      return this.request('POST', this.buildPath('/:branch/validate-references/...path', params), body)
    },

    /** PATCH /:branch/rename-entry/...path */
    renameEntry: (params: Record<string, string>, body: RenameEntryBody): Promise<RenameEntryResponse> => {
      return this.request('PATCH', this.buildPath('/:branch/rename-entry/...path', params), body)
    },

    /** GET /:branch/reference-options */
    getReferenceOptions: (params: Record<string, string>): Promise<ReferenceOptionsResponse> => {
      return this.request('GET', this.buildPath('/:branch/reference-options', params))
    },

    /** POST /:branch/resolve-references */
    resolveReferences: (params: Record<string, string>, body: ResolveReferencesBody): Promise<ResolveReferencesResponse> => {
      return this.request('POST', this.buildPath('/:branch/resolve-references', params), body)
    },
  }

  readonly entries = {
    /** GET /:branch/entries */
    list: (params: Record<string, string>): Promise<EntriesResponse> => {
      return this.request('GET', this.buildPath('/:branch/entries', params))
    },

    /** DELETE /:branch/entries/...entryPath */
    delete: (params: Record<string, string>): Promise<DeleteEntryResponse> => {
      return this.request('DELETE', this.buildPath('/:branch/entries/...entryPath', params))
    },
  }

  readonly assets = {
    /** POST /assets/presign */
    presign: (body: PresignAssetBody): Promise<PresignAssetResponse> => {
      return this.request('POST', '/assets/presign', body)
    },

    /** POST /assets/finalize */
    finalize: (body: FinalizeAssetBody): Promise<FinalizeAssetResponse> => {
      return this.request('POST', '/assets/finalize', body)
    },

    /** POST /assets/upload: multipart upload, hand-written because the generic template only knows JSON bodies. */
    uploadProxied: (file: File, options?: { filename?: string }): Promise<FinalizeAssetResponse> => {
      const formData = new FormData()
      formData.append('file', file)
      if (options?.filename) {
        formData.append('filename', options.filename)
      }
      return this.request('POST', '/assets/upload', formData)
    },

    /** GET /assets */
    list: (params: Record<string, string>): Promise<AssetsListResponse> => {
      return this.request('GET', this.buildPath('/assets', params))
    },

    /** DELETE /assets */
    delete: (params: Record<string, string>): Promise<AssetDeleteResponse> => {
      return this.request('DELETE', this.buildPath('/assets', params))
    },
  }

  readonly permissions = {
    /** GET /permissions */
    get: (): Promise<PermissionsResponse> => {
      return this.request('GET', '/permissions')
    },

    /** PUT /permissions */
    update: (body: UpdatePermissionsBody): Promise<PermissionsResponse> => {
      return this.request('PUT', '/permissions', body)
    },

    /** GET /users/search */
    searchUsers: (params: Record<string, string>): Promise<SearchUsersResponse> => {
      return this.request('GET', this.buildPath('/users/search', params))
    },

    /** GET /groups */
    listGroups: (): Promise<ListGroupsResponse> => {
      return this.request('GET', '/groups')
    },

    /** GET /users/:userId */
    getUserMetadata: (params: Record<string, string>): Promise<GetUserMetadataResponse> => {
      return this.request('GET', this.buildPath('/users/:userId', params))
    },
  }

  readonly groups = {
    /** GET /groups/internal */
    getInternal: (): Promise<InternalGroupsResponse> => {
      return this.request('GET', '/groups/internal')
    },

    /** PUT /groups/internal */
    updateInternal: (body: UpdateInternalGroupsBody): Promise<UpdateInternalGroupsResponse> => {
      return this.request('PUT', '/groups/internal', body)
    },

    /** GET /groups/search */
    searchExternal: (params: Record<string, string>): Promise<ExternalGroupsResponse> => {
      return this.request('GET', this.buildPath('/groups/search', params))
    },
  }

  readonly user = {
    /** GET /whoami */
    whoami: (): Promise<UserInfoResponse> => {
      return this.request('GET', '/whoami')
    },
  }

  readonly schema = {
    /** GET /:branch/schema */
    get: (params: Record<string, string>): Promise<GetSchemaApiResponse> => {
      return this.request('GET', this.buildPath('/:branch/schema', params))
    },

    /** GET /:branch/schema/collection/...collectionPath */
    getCollection: (params: Record<string, string>): Promise<GetCollectionApiResponse> => {
      return this.request('GET', this.buildPath('/:branch/schema/collection/...collectionPath', params))
    },

    /** POST /:branch/schema/collections */
    createCollection: (params: Record<string, string>, body: CreateCollectionInput): Promise<CreateCollectionApiResponse> => {
      return this.request('POST', this.buildPath('/:branch/schema/collections', params), body)
    },

    /** PATCH /:branch/schema/collection/...collectionPath */
    updateCollection: (params: Record<string, string>, body: UpdateCollectionInput): Promise<UpdateCollectionApiResponse> => {
      return this.request('PATCH', this.buildPath('/:branch/schema/collection/...collectionPath', params), body)
    },

    /** DELETE /:branch/schema/collection/...collectionPath */
    deleteCollection: (params: Record<string, string>): Promise<DeleteCollectionApiResponse> => {
      return this.request('DELETE', this.buildPath('/:branch/schema/collection/...collectionPath', params))
    },

    /** POST /:branch/schema/entry-types/...collectionPath */
    addEntryType: (params: Record<string, string>, body: CreateEntryTypeInput): Promise<AddEntryTypeApiResponse> => {
      return this.request('POST', this.buildPath('/:branch/schema/entry-types/...collectionPath', params), body)
    },

    /** PATCH /:branch/schema/entry-types/:entryTypeName/...collectionPath */
    updateEntryType: (params: Record<string, string>, body: UpdateEntryTypeInput): Promise<UpdateEntryTypeApiResponse> => {
      return this.request('PATCH', this.buildPath('/:branch/schema/entry-types/:entryTypeName/...collectionPath', params), body)
    },

    /** DELETE /:branch/schema/entry-types/:entryTypeName/...collectionPath */
    removeEntryType: (params: Record<string, string>): Promise<RemoveEntryTypeApiResponse> => {
      return this.request('DELETE', this.buildPath('/:branch/schema/entry-types/:entryTypeName/...collectionPath', params))
    },

    /** PATCH /:branch/schema/order/...collectionPath */
    updateOrder: (params: Record<string, string>, body: UpdateOrderBody): Promise<UpdateOrderApiResponse> => {
      return this.request('PATCH', this.buildPath('/:branch/schema/order/...collectionPath', params), body)
    },

    /** POST /:branch/schema/invalidate-cache */
    invalidateSchemaCache: (params: Record<string, string>): Promise<InvalidateSchemaCacheApiResponse> => {
      return this.request('POST', this.buildPath('/:branch/schema/invalidate-cache', params))
    },
  }

  readonly admin = {
    /** GET /admin/branch-health */
    branchHealth: (): Promise<BranchHealthResponse> => {
      return this.request('GET', '/admin/branch-health')
    },

    /** POST /admin/branch-dirs/:dirName/purge */
    purgeBranchDir: (params: Record<string, string>): Promise<PurgeBranchDirResponse> => {
      return this.request('POST', this.buildPath('/admin/branch-dirs/:dirName/purge', params))
    },

    /** POST /admin/branch-dirs/:dirName/repair-metadata */
    repairBranchDir: (params: Record<string, string>): Promise<RepairBranchDirResponse> => {
      return this.request('POST', this.buildPath('/admin/branch-dirs/:dirName/repair-metadata', params))
    },

    /** POST /admin/branch-dirs/:dirName/repair-content-duplicates */
    repairContentDuplicates: (params: Record<string, string>): Promise<RepairContentDuplicatesResponse> => {
      return this.request('POST', this.buildPath('/admin/branch-dirs/:dirName/repair-content-duplicates', params))
    },

    /** GET /admin/status */
    status: (): Promise<AdminStatusResponse> => {
      return this.request('GET', '/admin/status')
    },

    /** GET /admin/tasks/:status */
    listTasks: (params: Record<string, string>): Promise<AdminTasksResponse> => {
      return this.request('GET', this.buildPath('/admin/tasks/:status', params))
    },

    /** POST /admin/tasks/:taskId/retry */
    retryTask: (params: Record<string, string>): Promise<AdminRetryTaskResponse> => {
      return this.request('POST', this.buildPath('/admin/tasks/:taskId/retry', params))
    },

    /** DELETE /admin/tasks/:status/:fileName */
    deleteTask: (params: Record<string, string>): Promise<AdminDeleteTaskResponse> => {
      return this.request('DELETE', this.buildPath('/admin/tasks/:status/:fileName', params))
    },
  }

  constructor(options: ApiClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? '/api/canopycms'
    // An unbound fetch throws "Illegal invocation" in browsers; Node has no window.
    this.fetchFn = options.fetch ?? (typeof window !== 'undefined' ? fetch.bind(window) : fetch)
    this.trailingSlash = options.trailingSlash ?? readTrailingSlashEnv()
    this.onUnauthorized = options.onUnauthorized
  }

  private buildPath(template: string, params: Record<string, string>): string {
    let result = template
    const queryParams: Record<string, string> = {}

    for (const [key, value] of Object.entries(params)) {
      const pathParamPattern = `:${key}`
      const restParamPattern = `...${key}`

      if (result.includes(pathParamPattern)) {
        result = result.replace(pathParamPattern, encodeURIComponent(String(value)))
      } else if (result.includes(restParamPattern)) {
        // For rest parameters, encode each segment separately to preserve slashes
        const encoded = String(value).split('/').map(segment => encodeURIComponent(segment)).join('/')
        result = result.replace(restParamPattern, encoded)
      } else {
        queryParams[key] = value
      }
    }

    if (Object.keys(queryParams).length > 0) {
      const queryString = Object.entries(queryParams)
        .map(([key, value]) => {
          // Spaces encode as '+' in the query string.
          return `${encodeURIComponent(key)}=${encodeURIComponent(String(value)).replace(/%20/g, '+')}`
        })
        .join('&')
      result = `${result}?${queryString}`
    }

    return result
  }

  private async request<T = unknown>(
    method: string,
    path: string,
    body?: unknown,
    headers: Record<string, string> = {}
  ): Promise<T> {
    const url = `${this.baseUrl}${this.trailingSlash ? withTrailingSlash(path) : path}`

    const requestHeaders: Record<string, string> = {
      ...headers,
    }

    let requestBody: BodyInit | undefined

    if (body !== undefined) {
      if (body instanceof FormData) {
        // No Content-Type for FormData: the browser sets it with the boundary. A
        // FormData body cannot carry x-amz-content-sha256 (the boundary is generated
        // at send time), so it 403s behind the CloudFront OAC prod shape -- see
        // docs/deploying-to-aws.md.
        requestBody = body
      } else {
        requestHeaders['Content-Type'] = 'application/json'
        requestBody = JSON.stringify(body)

        // CloudFront's OAC signs the origin request but never hashes the payload, so
        // the viewer request must carry x-amz-content-sha256 or the OAC-protected
        // Function URL returns 403. Harmless on non-AWS deployments.
        const contentHash = await computeContentSha256Hex(requestBody)
        if (contentHash) {
          requestHeaders['x-amz-content-sha256'] = contentHash
        }
      }
    }

    const init: RequestInit = {
      method,
      headers: requestHeaders,
    }

    if (requestBody !== undefined) {
      init.body = requestBody
    }

    let response = await this.fetchFn(url, init)
    // A body from in front of the API (a proxy or CDN error page) may be empty, not JSON, or
    // not an ApiResponse; every such body becomes an `ok: false` ApiResponse, never a throw.
    let parsed: unknown = await response.json().catch(() => undefined)
    // A 429 no handler wrote is a throttle in front of the API, such as Lambda's concurrency
    // cap, which answers before the function runs. The request was never handled, so
    // resending it is safe for writes too.
    for (let attempt = 0; response.status === 429 && !isApiResponseBody(parsed); attempt++) {
      const delay = throttleRetryDelayMs(response, attempt)
      if (delay === undefined) break
      await sleep(delay)
      response = await this.fetchFn(url, init)
      parsed = await response.json().catch(() => undefined)
    }
    if (response.status === 401) {
      this.onUnauthorized?.()
      return { ok: false, status: 401, error: errorFromBody(parsed) ?? 'Unauthorized' } as T
    }
    if (isApiResponseBody(parsed)) return parsed as T
    const converted = {
      ok: false,
      status: response.status,
      error: errorFromBody(parsed) ?? `Unexpected response from server (HTTP ${response.status})`,
    }
    convertedResponses.add(converted)
    return converted as T
  }
}

/**
 * Base wait before each resend of a throttled request. A throttle from a burst of cold starts
 * clears as they finish, so the waits span a few seconds.
 */
const THROTTLE_RETRY_DELAYS_MS = [250, 1000, 3000]

/** The longest `Retry-After` waited; a throttle asking for longer is reported, not resent. */
const MAX_RETRY_AFTER_MS = 5000

/**
 * The wait before resend `attempt`, or undefined when there is to be no resend: the attempts
 * are used up, or `Retry-After` asks for longer than {@link MAX_RETRY_AFTER_MS}. The base delay,
 * or `Retry-After` when longer, plus up to half the base again, so requests throttled in one
 * burst do not resend in lockstep.
 */
function throttleRetryDelayMs(response: Response, attempt: number): number | undefined {
  const base = THROTTLE_RETRY_DELAYS_MS[attempt]
  if (base === undefined) return undefined
  // Delta-seconds only; an HTTP-date or a blank value falls back to the base delay. A custom
  // `fetch` option may return a Response-like without headers.
  const header = (response.headers as Headers | undefined)?.get('retry-after')?.trim()
  const retryAfter = header ? Number(header) : Number.NaN
  let wait = base
  if (Number.isFinite(retryAfter) && retryAfter >= 0) {
    const ms = retryAfter * 1000
    if (ms > MAX_RETRY_AFTER_MS) return undefined
    wait = Math.max(ms, base)
  }
  return wait + Math.random() * base * 0.5
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

const convertedResponses = new WeakSet<object>()

/**
 * Whether `result` was converted from a body no CanopyCMS handler wrote (a proxy or CDN
 * error page), so its status says nothing about the API itself.
 */
export function isNonApiResponse(result: object): boolean {
  return convertedResponses.has(result)
}

/** The `error` string of a JSON body, when it has one. */
function errorFromBody(body: unknown): string | undefined {
  return typeof body === 'object' && body !== null && 'error' in body && typeof body.error === 'string'
    ? body.error
    : undefined
}

/** Whether a parsed body has the `{ ok, status, ... }` shape every handler returns. */
function isApiResponseBody(body: unknown): body is ApiResponse {
  return typeof body === 'object' && body !== null && 'ok' in body && typeof body.ok === 'boolean'
}

/** Create a {@link CanopyApiClient}; pass a custom fetch for tests. */
export function createApiClient(options?: ApiClientOptions): CanopyApiClient {
  return new CanopyApiClient(options)
}
