/**
 * Typed API client for CanopyCMS.
 *
 * AUTO-GENERATED by scripts/generate-client.ts
 * Do not edit this file manually - changes will be overwritten.
 */

// Type imports
import type {
  BranchDeleteResponse,
  BranchListResponse,
  BranchResponse,
  CreateBranchBody,
  UpdateBranchAccessBody,
} from './branch'
import type { BranchMergeResponse } from './branch-status'
import type { RequestChangesBody } from './branch-review'
import type {
  AddCommentBody,
  AddCommentResponse,
  CommentsResponse,
  ResolveCommentResponse,
} from './comments'
import type {
  ContentReadResponse,
  ContentWriteResponse,
  ReferenceValidationResponse,
  ValidateReferencesBody,
  WriteContentBody,
} from './content'
import type { ReferenceOptionsResponse } from './reference-options'
import type { ResolveReferencesBody, ResolveReferencesResponse } from './resolve-references'
import type { DeleteEntryResponse, EntriesResponse } from './entries'
import type {
  AssetDeleteResponse,
  AssetUploadResponse,
  AssetsListResponse,
  UploadAssetBody,
} from './assets'
import type {
  GetUserMetadataResponse,
  ListGroupsResponse,
  PermissionsResponse,
  SearchUsersResponse,
  UpdatePermissionsBody,
} from './permissions'
import type {
  ExternalGroupsResponse,
  InternalGroupsResponse,
  UpdateInternalGroupsBody,
  UpdateInternalGroupsResponse,
} from './groups'
import type { UserInfoResponse } from './user'
import type {
  AddEntryTypeApiResponse,
  CreateCollectionApiResponse,
  DeleteCollectionApiResponse,
  GetCollectionApiResponse,
  GetSchemaApiResponse,
  RemoveEntryTypeApiResponse,
  UpdateCollectionApiResponse,
  UpdateEntryTypeApiResponse,
  UpdateOrderApiResponse,
  UpdateOrderBody,
} from './schema'
import type {
  CreateCollectionInput,
  CreateEntryTypeInput,
  UpdateCollectionInput,
  UpdateEntryTypeInput,
} from './../schema/schema-store-types'

/**
 * Options for creating an ApiClient
 */
export interface ApiClientOptions {
  /**
   * Base URL for API requests. Defaults to '/api/canopycms'
   */
  baseUrl?: string

  /**
   * Custom fetch implementation (useful for testing)
   */
  fetch?: typeof fetch
}

/**
 * Lightweight typed API client for CanopyCMS.
 *
 * Provides type-safe methods for all API endpoints with centralized
 * response unwrapping and error handling.
 *
 * @example Browser usage
 * ```ts
 * const client = createApiClient()
 * const branches = await client.branches.list()
 * if (branches.ok) {
 *   console.log(branches.data.branches)
 * }
 * ```
 *
 * @example Test usage
 * ```ts
 * const client = createApiClient({
 *   fetch: mockFetch
 * })
 * ```
 */
export class CanopyApiClient {
  private baseUrl: string
  private fetchFn: typeof fetch

  // ========== Auto-Generated Client Namespaces ==========
  // Generated by scripts/generate-client.ts - DO NOT EDIT MANUALLY

  /**
   * branches - Auto-generated methods
   */
  readonly branches = {
    /**
     * list - GET /branches
     */
    list: (): Promise<BranchListResponse> => {
      return this.request('GET', '/branches')
    },

    /**
     * create - POST /branches
     */
    create: (body: CreateBranchBody): Promise<BranchResponse> => {
      return this.request('POST', '/branches', body)
    },

    /**
     * delete - DELETE /:branch
     */
    delete: (params: Record<string, string>): Promise<BranchDeleteResponse> => {
      return this.request('DELETE', this.buildPath('/:branch', params))
    },

    /**
     * updateAccess - PATCH /:branch/access
     */
    updateAccess: (
      params: Record<string, string>,
      body: UpdateBranchAccessBody,
    ): Promise<BranchResponse> => {
      return this.request('PATCH', this.buildPath('/:branch/access', params), body)
    },
  }

  /**
   * workflow - Auto-generated methods
   */
  readonly workflow = {
    /**
     * withdraw - POST /:branch/withdraw
     */
    withdraw: (params: Record<string, string>): Promise<BranchResponse> => {
      return this.request('POST', this.buildPath('/:branch/withdraw', params))
    },

    /**
     * requestChanges - POST /:branch/request-changes
     */
    requestChanges: (
      params: Record<string, string>,
      body: RequestChangesBody,
    ): Promise<BranchResponse> => {
      return this.request('POST', this.buildPath('/:branch/request-changes', params), body)
    },

    /**
     * approve - POST /:branch/approve
     */
    approve: (params: Record<string, string>): Promise<BranchResponse> => {
      return this.request('POST', this.buildPath('/:branch/approve', params))
    },

    /**
     * markMerged - POST /:branch/mark-merged
     */
    markMerged: (params: Record<string, string>): Promise<BranchMergeResponse> => {
      return this.request('POST', this.buildPath('/:branch/mark-merged', params))
    },

    /**
     * getStatus - GET /:branch/status
     */
    getStatus: (params: Record<string, string>): Promise<BranchResponse> => {
      return this.request('GET', this.buildPath('/:branch/status', params))
    },

    /**
     * submit - POST /:branch/submit
     */
    submit: (params: Record<string, string>): Promise<BranchResponse> => {
      return this.request('POST', this.buildPath('/:branch/submit', params))
    },
  }

  /**
   * comments - Auto-generated methods
   */
  readonly comments = {
    /**
     * list - GET /:branch/comments
     */
    list: (params: Record<string, string>): Promise<CommentsResponse> => {
      return this.request('GET', this.buildPath('/:branch/comments', params))
    },

    /**
     * add - POST /:branch/comments
     */
    add: (params: Record<string, string>, body: AddCommentBody): Promise<AddCommentResponse> => {
      return this.request('POST', this.buildPath('/:branch/comments', params), body)
    },

    /**
     * resolve - POST /:branch/comments/:threadId/resolve
     */
    resolve: (params: Record<string, string>): Promise<ResolveCommentResponse> => {
      return this.request('POST', this.buildPath('/:branch/comments/:threadId/resolve', params))
    },
  }

  /**
   * content - Auto-generated methods
   */
  readonly content = {
    /**
     * read - GET /:branch/content/...path
     */
    read: (params: Record<string, string>): Promise<ContentReadResponse> => {
      return this.request('GET', this.buildPath('/:branch/content/...path', params))
    },

    /**
     * write - PUT /:branch/content/...path
     */
    write: (
      params: Record<string, string>,
      body: WriteContentBody,
    ): Promise<ContentWriteResponse> => {
      return this.request('PUT', this.buildPath('/:branch/content/...path', params), body)
    },

    /**
     * validateReferences - POST /:branch/validate-references/...path
     */
    validateReferences: (
      params: Record<string, string>,
      body: ValidateReferencesBody,
    ): Promise<ReferenceValidationResponse> => {
      return this.request(
        'POST',
        this.buildPath('/:branch/validate-references/...path', params),
        body,
      )
    },

    /**
     * getReferenceOptions - GET /:branch/reference-options
     */
    getReferenceOptions: (params: Record<string, string>): Promise<ReferenceOptionsResponse> => {
      return this.request('GET', this.buildPath('/:branch/reference-options', params))
    },

    /**
     * resolveReferences - POST /:branch/resolve-references
     */
    resolveReferences: (
      params: Record<string, string>,
      body: ResolveReferencesBody,
    ): Promise<ResolveReferencesResponse> => {
      return this.request('POST', this.buildPath('/:branch/resolve-references', params), body)
    },
  }

  /**
   * entries - Auto-generated methods
   */
  readonly entries = {
    /**
     * list - GET /:branch/entries
     */
    list: (params: Record<string, string>): Promise<EntriesResponse> => {
      return this.request('GET', this.buildPath('/:branch/entries', params))
    },

    /**
     * delete - DELETE /:branch/entries/...entryPath
     */
    delete: (params: Record<string, string>): Promise<DeleteEntryResponse> => {
      return this.request('DELETE', this.buildPath('/:branch/entries/...entryPath', params))
    },
  }

  /**
   * assets - Auto-generated methods
   */
  readonly assets = {
    /**
     * list - GET /assets
     */
    list: (): Promise<AssetsListResponse> => {
      return this.request('GET', '/assets')
    },

    /**
     * upload - POST /assets
     */
    upload: (body: UploadAssetBody): Promise<AssetUploadResponse> => {
      return this.request('POST', '/assets', body)
    },

    /**
     * delete - DELETE /assets
     */
    delete: (): Promise<AssetDeleteResponse> => {
      return this.request('DELETE', '/assets')
    },
  }

  /**
   * permissions - Auto-generated methods
   */
  readonly permissions = {
    /**
     * get - GET /permissions
     */
    get: (): Promise<PermissionsResponse> => {
      return this.request('GET', '/permissions')
    },

    /**
     * update - PUT /permissions
     */
    update: (body: UpdatePermissionsBody): Promise<PermissionsResponse> => {
      return this.request('PUT', '/permissions', body)
    },

    /**
     * searchUsers - GET /users/search
     */
    searchUsers: (params: Record<string, string>): Promise<SearchUsersResponse> => {
      return this.request('GET', this.buildPath('/users/search', params))
    },

    /**
     * listGroups - GET /groups
     */
    listGroups: (): Promise<ListGroupsResponse> => {
      return this.request('GET', '/groups')
    },

    /**
     * getUserMetadata - GET /users/:userId
     */
    getUserMetadata: (params: Record<string, string>): Promise<GetUserMetadataResponse> => {
      return this.request('GET', this.buildPath('/users/:userId', params))
    },
  }

  /**
   * groups - Auto-generated methods
   */
  readonly groups = {
    /**
     * getInternal - GET /groups/internal
     */
    getInternal: (): Promise<InternalGroupsResponse> => {
      return this.request('GET', '/groups/internal')
    },

    /**
     * updateInternal - PUT /groups/internal
     */
    updateInternal: (body: UpdateInternalGroupsBody): Promise<UpdateInternalGroupsResponse> => {
      return this.request('PUT', '/groups/internal', body)
    },

    /**
     * searchExternal - GET /groups/search
     */
    searchExternal: (params: Record<string, string>): Promise<ExternalGroupsResponse> => {
      return this.request('GET', this.buildPath('/groups/search', params))
    },
  }

  /**
   * user - Auto-generated methods
   */
  readonly user = {
    /**
     * whoami - GET /whoami
     */
    whoami: (): Promise<UserInfoResponse> => {
      return this.request('GET', '/whoami')
    },
  }

  /**
   * schema - Auto-generated methods
   */
  readonly schema = {
    /**
     * get - GET /:branch/schema
     */
    get: (params: Record<string, string>): Promise<GetSchemaApiResponse> => {
      return this.request('GET', this.buildPath('/:branch/schema', params))
    },

    /**
     * getCollection - GET /:branch/schema/collection/...collectionPath
     */
    getCollection: (params: Record<string, string>): Promise<GetCollectionApiResponse> => {
      return this.request(
        'GET',
        this.buildPath('/:branch/schema/collection/...collectionPath', params),
      )
    },

    /**
     * createCollection - POST /:branch/schema/collections
     */
    createCollection: (
      params: Record<string, string>,
      body: CreateCollectionInput,
    ): Promise<CreateCollectionApiResponse> => {
      return this.request('POST', this.buildPath('/:branch/schema/collections', params), body)
    },

    /**
     * updateCollection - PATCH /:branch/schema/collection/...collectionPath
     */
    updateCollection: (
      params: Record<string, string>,
      body: UpdateCollectionInput,
    ): Promise<UpdateCollectionApiResponse> => {
      return this.request(
        'PATCH',
        this.buildPath('/:branch/schema/collection/...collectionPath', params),
        body,
      )
    },

    /**
     * deleteCollection - DELETE /:branch/schema/collection/...collectionPath
     */
    deleteCollection: (params: Record<string, string>): Promise<DeleteCollectionApiResponse> => {
      return this.request(
        'DELETE',
        this.buildPath('/:branch/schema/collection/...collectionPath', params),
      )
    },

    /**
     * addEntryType - POST /:branch/schema/entry-types/...collectionPath
     */
    addEntryType: (
      params: Record<string, string>,
      body: CreateEntryTypeInput,
    ): Promise<AddEntryTypeApiResponse> => {
      return this.request(
        'POST',
        this.buildPath('/:branch/schema/entry-types/...collectionPath', params),
        body,
      )
    },

    /**
     * updateEntryType - PATCH /:branch/schema/entry-types/:entryTypeName/...collectionPath
     */
    updateEntryType: (
      params: Record<string, string>,
      body: UpdateEntryTypeInput,
    ): Promise<UpdateEntryTypeApiResponse> => {
      return this.request(
        'PATCH',
        this.buildPath('/:branch/schema/entry-types/:entryTypeName/...collectionPath', params),
        body,
      )
    },

    /**
     * removeEntryType - DELETE /:branch/schema/entry-types/:entryTypeName/...collectionPath
     */
    removeEntryType: (params: Record<string, string>): Promise<RemoveEntryTypeApiResponse> => {
      return this.request(
        'DELETE',
        this.buildPath('/:branch/schema/entry-types/:entryTypeName/...collectionPath', params),
      )
    },

    /**
     * updateOrder - PATCH /:branch/schema/order/...collectionPath
     */
    updateOrder: (
      params: Record<string, string>,
      body: UpdateOrderBody,
    ): Promise<UpdateOrderApiResponse> => {
      return this.request(
        'PATCH',
        this.buildPath('/:branch/schema/order/...collectionPath', params),
        body,
      )
    },
  }

  constructor(options: ApiClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? '/api/canopycms'
    // Bind fetch to window to prevent "Illegal invocation" errors in browsers
    // In Node.js tests, window is undefined so use fetch directly
    this.fetchFn = options.fetch ?? (typeof window !== 'undefined' ? fetch.bind(window) : fetch)
  }

  // ========== Low-level HTTP methods ==========

  private buildPath(template: string, params: Record<string, string>): string {
    let result = template
    const queryParams: Record<string, string> = {}

    for (const [key, value] of Object.entries(params)) {
      // Check if this param is in the path template
      const pathParamPattern = `:${key}`
      const restParamPattern = `...${key}`

      if (result.includes(pathParamPattern)) {
        result = result.replace(pathParamPattern, encodeURIComponent(String(value)))
      } else if (result.includes(restParamPattern)) {
        // For rest parameters, encode each segment separately to preserve slashes
        const encoded = String(value)
          .split('/')
          .map((segment) => encodeURIComponent(segment))
          .join('/')
        result = result.replace(restParamPattern, encoded)
      } else {
        // Not in path template, so it's a query param
        queryParams[key] = value
      }
    }

    // Append query params if any
    if (Object.keys(queryParams).length > 0) {
      const queryString = Object.entries(queryParams)
        .map(([key, value]) => {
          // URL-encode with proper handling of spaces and special chars
          return `${encodeURIComponent(key)}=${encodeURIComponent(String(value)).replace(/%20/g, '+')}`
        })
        .join('&')
      result = `${result}?${queryString}`
    }

    return result
  }

  private async request<T = unknown>(
    method: string,
    path: string,
    body?: unknown,
    headers: Record<string, string> = {},
  ): Promise<T> {
    const url = `${this.baseUrl}${path}`

    const requestHeaders: Record<string, string> = {
      ...headers,
    }

    if (body !== undefined && !(body instanceof FormData)) {
      requestHeaders['Content-Type'] = 'application/json'
    }

    const init: RequestInit = {
      method,
      headers: requestHeaders,
    }

    if (body !== undefined) {
      if (body instanceof FormData) {
        // Don't set Content-Type for FormData - browser will set it with boundary
        init.body = body
      } else {
        init.body = JSON.stringify(body)
      }
    }

    const response = await this.fetchFn(url, init)
    const payload = await response.json()

    // All responses use ApiResponse format: { ok, status, data?, error? }
    return payload as T
  }
}

/**
 * Create a new API client instance
 */
export function createApiClient(options?: ApiClientOptions): CanopyApiClient {
  return new CanopyApiClient(options)
}
