/**
 * Computes the `x-amz-content-sha256` header value required by CloudFront's
 * Origin Access Control (OAC) SigV4 signing when a request carries a body.
 *
 * Documented AWS behavior: CloudFront signs origin requests to OAC-protected
 * Lambda Function URLs, but it never hashes the payload itself - it forwards
 * whatever `x-amz-content-sha256` header value the viewer request already
 * has. If a request has a body and this header is missing, Lambda's
 * signature verification fails and the origin responds 403. See
 * docs/deploying-to-aws.md for the full explanation.
 *
 * Uses WebCrypto (available in secure-context browsers and in Node >= 18) to
 * compute the lowercase-hex SHA-256 digest of the exact bytes sent as the
 * request body.
 */

/**
 * Hash a string request body (e.g. a JSON-serialized payload).
 *
 * Returns `undefined` if WebCrypto is unavailable (for example a dev server
 * running over plain http, which is not a secure context) so callers can
 * skip the header rather than throw - production deployments are always
 * https.
 */
export async function computeContentSha256Hex(body: string): Promise<string | undefined> {
  return computeContentSha256HexFromBytes(new TextEncoder().encode(body))
}

/**
 * Hash a raw-bytes request body (e.g. an ArrayBuffer or Blob upload).
 *
 * Note: this cannot be used for `FormData` bodies - the multipart boundary
 * is generated by the runtime at send time, so the final byte stream isn't
 * known until after the request would already need to be signed.
 */
export async function computeContentSha256HexFromBytes(
  bytes: BufferSource,
): Promise<string | undefined> {
  const subtle = globalThis.crypto?.subtle
  if (!subtle) return undefined

  const digest = await subtle.digest('SHA-256', bytes)
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('')
}
